# Provisioners (higher weight = higher priority):
# dv2:  weight 10, cpu 500 = 250 VMs
# dv3:  weight  9, cpu 500 = 250 VMs
# dsv2: weight  7, cpu 500 = 250 VMs
# dsv3: weight  6, cpu 500 = 250 VMs

# (don't forget to delete the default Provisioner, if any!)

apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: dv2
spec:
  weight: 10

  ttlSecondsAfterEmpty: 3600

  limits:
    resources:
      cpu: 500 # for 250 VMs

  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values: [Standard_D2_v2]

   # currently provisioning nodes with EnableAcceleratedNetworking:true, so need SKUs capable of that
  - key: karpenter.k8s.azure/sku-networking-accelerated
    operator: In
    values: ['true']

  providerRef:
    name: default
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: dv3
spec:
  weight: 9

  ttlSecondsAfterEmpty: 3600

  limits:
    resources:
      cpu: 500 # for 250 VMs

  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values: [Standard_D2_v3]

   # currently provisioning nodes with EnableAcceleratedNetworking:true, so need SKUs capable of that
  - key: karpenter.k8s.azure/sku-networking-accelerated
    operator: In
    values: ['true']

  providerRef:
    name: default
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: dsv2
spec:
  weight: 8

  ttlSecondsAfterEmpty: 3600

  limits:
    resources:
      cpu: 500 # for 250 VMs

  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values: [Standard_DS2_v2]

   # currently provisioning nodes with EnableAcceleratedNetworking:true, so need SKUs capable of that
  - key: karpenter.k8s.azure/sku-networking-accelerated
    operator: In
    values: ['true']

  providerRef:
    name: default
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: dsv3
spec:
  weight: 7

  ttlSecondsAfterEmpty: 3600

  limits:
    resources:
      cpu: 500 # for 250 VMs

  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values: [Standard_D2s_v3]

   # currently provisioning nodes with EnableAcceleratedNetworking:true, so need SKUs capable of that
  - key: karpenter.k8s.azure/sku-networking-accelerated
    operator: In
    values: ['true']

  providerRef:
    name: default
---
apiVersion: karpenter.k8s.azure/v1alpha1
kind: NodeTemplate
metadata:
  name: default
spec: {}
