/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/providers/instance/azure_client.go
//
// Generated by this command:
//
//	mockgen -source=pkg/providers/instance/azure_client.go -destination=pkg/fake/azure_client.go
//
package fake

import (
	context "context"
	reflect "reflect"

	runtime "github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	v4 "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentPoolsAPI is a mock of AgentPoolsAPI interface.
type MockAgentPoolsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAgentPoolsAPIMockRecorder
}

// MockAgentPoolsAPIMockRecorder is the mock recorder for MockAgentPoolsAPI.
type MockAgentPoolsAPIMockRecorder struct {
	mock *MockAgentPoolsAPI
}

// NewMockAgentPoolsAPI creates a new mock instance.
func NewMockAgentPoolsAPI(ctrl *gomock.Controller) *MockAgentPoolsAPI {
	mock := &MockAgentPoolsAPI{ctrl: ctrl}
	mock.recorder = &MockAgentPoolsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentPoolsAPI) EXPECT() *MockAgentPoolsAPIMockRecorder {
	return m.recorder
}

// BeginCreateOrUpdate mocks base method.
func (m *MockAgentPoolsAPI) BeginCreateOrUpdate(ctx context.Context, resourceGroupName, resourceName, agentPoolName string, parameters v4.AgentPool, options *v4.AgentPoolsClientBeginCreateOrUpdateOptions) (*runtime.Poller[v4.AgentPoolsClientCreateOrUpdateResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginCreateOrUpdate", ctx, resourceGroupName, resourceName, agentPoolName, parameters, options)
	ret0, _ := ret[0].(*runtime.Poller[v4.AgentPoolsClientCreateOrUpdateResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginCreateOrUpdate indicates an expected call of BeginCreateOrUpdate.
func (mr *MockAgentPoolsAPIMockRecorder) BeginCreateOrUpdate(ctx, resourceGroupName, resourceName, agentPoolName, parameters, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginCreateOrUpdate", reflect.TypeOf((*MockAgentPoolsAPI)(nil).BeginCreateOrUpdate), ctx, resourceGroupName, resourceName, agentPoolName, parameters, options)
}

// BeginDelete mocks base method.
func (m *MockAgentPoolsAPI) BeginDelete(ctx context.Context, resourceGroupName, resourceName, agentPoolName string, options *v4.AgentPoolsClientBeginDeleteOptions) (*runtime.Poller[v4.AgentPoolsClientDeleteResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginDelete", ctx, resourceGroupName, resourceName, agentPoolName, options)
	ret0, _ := ret[0].(*runtime.Poller[v4.AgentPoolsClientDeleteResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginDelete indicates an expected call of BeginDelete.
func (mr *MockAgentPoolsAPIMockRecorder) BeginDelete(ctx, resourceGroupName, resourceName, agentPoolName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginDelete", reflect.TypeOf((*MockAgentPoolsAPI)(nil).BeginDelete), ctx, resourceGroupName, resourceName, agentPoolName, options)
}

// Get mocks base method.
func (m *MockAgentPoolsAPI) Get(ctx context.Context, resourceGroupName, resourceName, agentPoolName string, options *v4.AgentPoolsClientGetOptions) (v4.AgentPoolsClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, resourceName, agentPoolName, options)
	ret0, _ := ret[0].(v4.AgentPoolsClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAgentPoolsAPIMockRecorder) Get(ctx, resourceGroupName, resourceName, agentPoolName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAgentPoolsAPI)(nil).Get), ctx, resourceGroupName, resourceName, agentPoolName, options)
}

// NewListPager mocks base method.
func (m *MockAgentPoolsAPI) NewListPager(resourceGroupName, resourceName string, options *v4.AgentPoolsClientListOptions) *runtime.Pager[v4.AgentPoolsClientListResponse] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListPager", resourceGroupName, resourceName, options)
	ret0, _ := ret[0].(*runtime.Pager[v4.AgentPoolsClientListResponse])
	return ret0
}

// NewListPager indicates an expected call of NewListPager.
func (mr *MockAgentPoolsAPIMockRecorder) NewListPager(resourceGroupName, resourceName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListPager", reflect.TypeOf((*MockAgentPoolsAPI)(nil).NewListPager), resourceGroupName, resourceName, options)
}
