---
apiVersion: karpenter.k8s.azure/v1alpha1
kind: NodeTemplate
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gpu-provisioner.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
