apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpu-provisioner.fullname" . }}-cert
  namespace:  {{ .Values.namespace }}
  labels:
    {{- include "gpu-provisioner.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
# data: {} # Injected by karpenter-webhook
