apiVersion: v2
name: gpu-provisioner
description: A Helm chart for gpu-provisioner
type: application
version: 0.4.3
appVersion: 0.4.3
sources:
  - https://github.com/Azure/gpu-provisioner
maintainers:
  - name: Fei-Guo
    email: vrgf2003@gmail.com
  - name: zhuangqh
  - name: rambohe-ch
    email: rambohe.ch@gmail.com
