apiVersion: v2
name: gpu-provisioner
description: A Helm chart for gpu-provisioner, an open-source GPU provisioning project built for Kubernetes.
type: application
version: 0.1.0
appVersion: 0.1.0
keywords:
  - gpu
  - cluster
  - node
  - scheduler
  - autoscaling
  - lifecycle
sources:
  - https://github.com/Fei-Guo/gpu-vmprovisioner
