apiVersion: karpenter.sh/v1
kind: NodeClaim
metadata:
  name: azure-linux-gpu-nodeclaim
  labels:
    kaito.sh/workspace: "llama-azure-linux"
    kaito.sh/node-image-family: "AzureLinux"
spec:
  nodeClassRef:
    apiVersion: karpenter.azure.com/v1alpha1
    kind: AKSNodeClass
    name: default
  requirements:
    # GPU instance type
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["Standard_NC12s_v3"]
    # Capacity type preference
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    # OS requirement
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]
    # NodePool label
    - key: karpenter.sh/nodepool
      operator: In
      values: ["kaito"]
  resources:
    requests:
      storage: "120Gi"
  taints:
    # GPU taint to ensure only GPU workloads are scheduled
    - key: "sku"
      value: "gpu"
      effect: NoSchedule
