apiVersion: karpenter.sh/v1alpha5
kind: Machine
metadata:
  name: test-machine
  labels:
    karpenter.sh/provisioner-name: default
spec:
  machineTemplateRef:
    name: default
  requirements:
  - key: karpenter.k8s.azure/sku-storage-premium-capable
    operator: In
    values:
    - "true"
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - Standard_D4ads_v5
    - Standard_D4as_v4
    - Standard_D4as_v5
    - Standard_D4ds_v4
    - Standard_D4ds_v5
    - Standard_D4lds_v5
    - Standard_D4ls_v5
    - Standard_D4s_v3
    - Standard_D4s_v4
    - Standard_D4s_v5
    - Standard_D8ads_v5
    - Standard_D8as_v4
    - Standard_D8as_v5
    - Standard_D8ds_v4
    - Standard_D8ds_v5
    - Standard_D8lds_v5
    - Standard_D8ls_v5
    - Standard_D8s_v3
    - Standard_D8s_v4
    - Standard_D8s_v5
    - Standard_DC4ds_v3
    - Standard_DC4s_v2
    - Standard_DC4s_v3
    - Standard_DC8ds_v3
    - Standard_DC8s_v3
    - Standard_DS12-1_v2
    - Standard_DS12-2_v2
    - Standard_DS12_v2
    - Standard_DS13-2_v2
    - Standard_DS13-4_v2
    - Standard_DS13_v2
    - Standard_DS3_v2
    - Standard_DS4_v2
  - key: karpenter.k8s.azure/sku-family
    operator: In
    values:
    - D
  - key: karpenter.sh/provisioner-name
    operator: In
    values:
    - default
  - key: karpenter.k8s.azure/sku-cpu
    operator: Lt
    values:
    - "33"
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: karpenter.k8s.azure/sku-networking-accelerated
    operator: In
    values:
    - "true"
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - Regular
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  resources:
    requests:
      cpu: 2310m
      memory: 725280Ki
      pods: "7"
status:
