apiVersion: karpenter.sh/v1alpha5
kind: Machine
metadata:
  name: heba-gpu-test
  labels:
    karpenter.sh/provisioner-name: default
spec:
  taints:
    - key: "sku"
      value: "gpu"
      effect: "NoSchedule"
  machineTemplateRef:
    name: default
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - Standard_D4ads_v5
    - Standard_D4as_v4
    - Standard_D4as_v5
    - Standard_D4ds_v4
    - Standard_D4ds_v5
    - Standard_D4lds_v5
    - Standard_D4ls_v5
    - Standard_D4s_v3
    - Standard_D4s_v4
    - Standard_D4s_v5
    - Standard_D8ads_v5
    - Standard_D8as_v4
    - Standard_D8as_v5
    - Standard_D8ds_v4
    - Standard_D8ds_v5
    - Standard_D8lds_v5
    - Standard_D8ls_v5
    - Standard_D8s_v3
    - Standard_D8s_v4
    - Standard_D8s_v5
    - Standard_DC4ds_v3
    - Standard_DC4s_v2
    - Standard_DC4s_v3
    - Standard_DC8ds_v3
    - Standard_DC8s_v3
    - Standard_DS12-1_v2
    - Standard_DS12-2_v2
    - Standard_DS12_v2
    - Standard_DS13-2_v2
    - Standard_DS13-4_v2
    - Standard_DS13_v2
    - Standard_DS3_v2
    - Standard_DS4_v2
    - Standard_NC6
    - Standard_NC12
    - Standard_NC24
    - Standard_NC24r
    - Standard_NC6s_v2
    - Standard_NC12s_v2
    - Standard_NC24s_v2
    - Standard_NC24rs_v2
    - Standard_NC6s_v3
    - Standard_NC12s_v3
    - Standard_NC24s_v3
    - Standard_NC24rs_v3
    - Standard_NC12
    - Standard_NC16as_T4_v3
    - Standard_NC24
    - Standard_NC24r
    - Standard_NC4as_T4_v3
    - Standard_NC64as_T4_v3
    - Standard_NC8as_T4_v3
    - Standard_ND6s
    - Standard_ND12s
    - Standard_ND24s
    - Standard_ND24rs
    - Standard_NV6
    - Standard_NV12
    - Standard_NV24
  - key: karpenter.sh/provisioner-name
    operator: In
    values:
    - default
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  resources:
    requests:
      cpu: 2310m
      memory: 725280Ki
      pods: "7"

status:
