[build]
base = "website/"
publish = "public"
command = "npm install; git submodule update --init --recursive; hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.86.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "npm install; git submodule update --init --recursive; hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.86.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm install; git submodule update --init --recursive; hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.86.0"

[context.branch-deploy]
command = "npm install; git submodule update --init --recursive; hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.86.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
