name: markdown link

on:
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          # this will only show errors in the output
          use-quiet-mode: 'yes'
          # this will show detailed HTTP status for checked links
          use-verbose-mode: 'yes'
          folder-path: './'
          base-branch: 'main'
          max-depth: '2'
